honey_shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    # path('remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

honey_shop/honey_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('auth/', include('users.urls')),
]

honey_shop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:name_id>/', views.detail, name='detail')
]

honey_shop/users/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls'))
]

honey_shop/cart/models.py
from django.db import models

# Create your models here.

honey_shop/shop/models.py
from django.db import models
from django.urls import reverse


class Products(models.Model):
    objects = None
    name = models.CharField(verbose_name='Наименование продукта', max_length=200)
    info = models.CharField(verbose_name='Описание продукта', max_length=200)
    price = models.FloatField(verbose_name='Цена продукта', default=0)

    def __str__(self):
        return f' {self.name} // {self.info} // {self.price}грн'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукти'

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

honey_shop/users/models.py
from django.db import models

# Create your models here.

honey_shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

honey_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartProductForm
from shop.models import Products


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(products=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartProductForm(initial={'quantity': item['quantity'], 'update': True})

    return render(request, 'cart/detail.html', {'cart': cart})

honey_shop/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .models import Products
from django.template import loader
from cart.forms import CartProductForm


def product_list(request):
    products = Products.objects.filter(available=True)
    return render(request,
                  'shop/product/list.html',
                  {'products': products})


def product_detail(request, id):
    product = get_object_or_404(Products,
                                id=id,
                                available=True)
    cart_product_form = CartProductForm()
    return render(request, 'shop/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


def index(request):
    products_list = Products.objects.order_by('name')
    return render(request, 'shop/title_list.html', {
        'products_list': products_list
    })


def detail(request, name_id):
    description = get_object_or_404(Products, pk=name_id)
    return render(request, 'shop/detail.html', {
        'description': description
    })

honey_shop/users/views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'dashboard.html')

honey_shop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h2>Твои покупки:</h2>
    <table class="cart">
        <thead>
        <tr>
            <th>Наименование</th>
            <th>Количество</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with products=item.products %}
                <tr>
                    <td>
                        <a href="{{ products.get_absolute_url }}">
                        </a>
                    </td>
                    <td>{{ products.name }}</td>
                    <td>{{ item.quantity }}</td>




                    <td><<a href="/shop/{{ names.id }}">Back to shop</a></td>

                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="Total">
            <td>Общая сумма:</td>
            <td colspan=""></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <td><<a href="/shop/{{ names.id }}">Back to shop</a></td>
    </p>
{% endblock %}

honey_shop/shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    {% block heading %}
        <h1> інтернет-магазин медової продукції </h1>
    {% endblock heading %}

    {% block content %}
    {% endblock content %}

   {% block final%}
    <hr>
    <p>
        <h4>наші контактні данні: mail, facebook...</h4>
    </p>
    <hr>
    {% endblock final %}
</body>
    <p style="color: #666666; background-color: #ef4444; padding: 20px;">
</html>

honey_shop/shop/templates/shop/detail.html
<h2>{{ description.info }}</h2>

<p class="price">ціна:{{ description.price }}грн</p>
<form action='{% url "cart:cart_add" description.id %}' method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
</form>

<p>
    <a href="/shop/{{ names.id }}">Back to shop</a>
</p>

honey_shop/shop/templates/shop/product/detail.html
shop/product/detail

<!--<p class="price">${{ product.price }}</p>-->
<!--<form action='{% url "cart:cart_add" product.id %}' method="post">-->
<!--    {{ cart_product_form }}-->
<!--    {% csrf_token %}-->
<!--    <input type="submit" value="Add to cart">-->
<!--</form>-->

honey_shop/shop/templates/shop/title_list.html
{% extends "shop/base.html" %}

<style>
    html, body{
        height: 100%;
        max-height: 100%;
    }
</style>

{% block content%}

Hello, {{ user.username|default:'Guest'}}!

<div>
    {% if user.is_authenticated%}
        <p><a href="{% url 'logout' %}">Вход</a></p>
        <p><a href="{% url 'password_change' %}">Сменить пароль</a></p>
    {% else %}
        <a href="{% url 'login' %}">Логин</a>
    {% endif %}
</div>

{% if products_list %}
    <ul>
        Список товарів:
        {% for names in products_list %}
        <h3><li><a href="/shop/{{ names.id }}">{{names.name}}</a></li></h3>
        {% endfor %}
    </ul>
{% else %}
    <p>NO</p>
{% endif %}


{% endblock content %}

honey_shop/users/templates/base.html
<h1> users auth </h1>

{% block content %}
{% endblock %}

honey_shop/users/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
Hello, {{ user.username|default:'Guest'}}!

<div>
    {% if user.is_authenticated%}
        <p><a href="{% url 'logout' %}"> Logout</a></p>
        <p><a href="{% url 'password_change' %}">Change password</a></p>
        <a href="/shop/{{ names.id }}">Back to shop</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>
{% endblock %}